import { docs_v1 as docsV1, drive_v3 as driveV3 } from 'googleapis';
import { GraphQLError } from 'graphql';
import { AvailableModels, Routes, coverLetterModelCost } from 'misc-glob';
import { Job, PrismaClient } from 'database';
import { VITE_FRONTEND_URL } from 'backend-env';

type CreateCoverLetterArgs = {
	drive: driveV3.Drive;
	docs: docsV1.Docs;
	folderId: string | undefined | null;
	companyName: string;
	jobName: string;
	content: string;
	job: Job;
	templateId: string;
	userId: string;
  model?: AvailableModels;
  prisma: PrismaClient;
};

export const CreateCoverLetter = async ({
  drive, docs, folderId, companyName, jobName, content, job, templateId, userId, model, prisma,
}: CreateCoverLetterArgs) => {
  // TODO: check if the user has enough credits to create a cover letter
  const templateGoogleId = await prisma.coverLetterTemplate.findUnique({
    where: {
      id: templateId,
      AND: {
        userId,
      },
    },
    select: {
      googleDocId: true,
    },
  });
  const newFile = await drive.files.copy({
    fileId: templateGoogleId?.googleDocId,
    requestBody: {
      name: `Cover Letter for ${companyName} - ${jobName}`,
      parents: folderId ? [folderId] : [],
      description: `Cover letter generated by JobStream - ${VITE_FRONTEND_URL}${Routes.Job.replace(':id', job.id)} - From ${job.url}`,
    },
  });

  if (!newFile.data.id) {
    throw new GraphQLError('Error creating new cover letter, fileID was not returned from google drive :(');
  }

  await docs.documents.batchUpdate({
    documentId: newFile.data.id,
    requestBody: {
      requests: [
        {
          replaceAllText: {
            containsText: {
              text: '{{job}}',
              matchCase: false,
            },
            replaceText: jobName,
          },
        },
        {
          replaceAllText: {
            containsText: {
              text: '{{content}}',
              matchCase: false,
            },
            replaceText: content,
          },
        },
      ],
    },
  });

  const cost = coverLetterModelCost[model || AvailableModels.GPT3_5_TURBO];

  const coverLetter = await prisma.generatedCoverLetter.create({
    data: {
      name: `Cover Letter for ${companyName} - ${jobName}`,
      googleDocId: newFile.data.id,
      user: {
        connect: {
          id: userId,
        },
      },
      job: {
        connect: {
          id: job.id,
        },
      },
      template: {
        connect: {
          id: templateId,
        },
      },
      Credits: {
        create: {
          userId,
          amount: -cost,
        },
      },
    },
  });

  return coverLetter;
};
